config/routes.rb
Rails.application.routes.draw do
  resources :document_histories
  resources :permissions
  resources :documents
  resources :departments do
    collection do
      get 'retriever'
    end
  end
  
  resources :roles
  resources :user_logins
  get 'sessions/new'
  get 'documents/:id/viewer', to: 'documents#viewer', as: 'view_history'
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  #get '*path' => redirect('/login')

  resources :users

  resources :sessions
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
	has_secure_password
 
	validates_uniqueness_of :username
	validates_presence_of :fname, :message => "^Please fill the First Name field!"
	validates :fname, length: { in: 2..30, too_short: "^First Name range should be between 2-30 characters", too_long: "^First Name range should be between 2-30 characters" }
	validates_presence_of :lname, :message => "^Please fill the Last Name field!"
	validates :lname, length: { in: 2..30, too_short: "^Last Name range should be between 2-30 characters", too_long: "^Last Name range should be between 2-30 characters" }
	validates :password, length: { in: 8..24, too_short: "^Your password is too short. Mininum password length is 8", too_long: "^Your password exceeds the allowable password length" }

	def fname_with_lname
		"#{fname} #{lname}"
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :authorize, only: [:edit, :update]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        #session[:user_id] = @user.id
        #format.html { redirect_back(fallback_location: root_path), notice: 'Thank you for signing up!' }
        user = User.find(@user.id)
        dept_head = Department.where("id = ?", @user.department_id).pluck(:user_id).first
        if dept_head != ""
          user.update_column(:user_id, dept_head)
        end
        format.html { redirect_to users_url, notice: 'successfully registered!' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        user = User.find(@user.id)
        dept_head = Department.where("id = ?", @user.department_id).pluck(:user_id).first
        if dept_head != ""
          user.update_column(:user_id, dept_head)
        end
        format.html { redirect_to users_url, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully deleted' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :fname, :lname, :email, :password, :role_id, :user_id, :department_id)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<% if User.where("id = ?", session[:user_id]).pluck(:role_id).first != 1 %>
  <% controller.redirect_to 'http://localhost:3000/documents' %>
<% end %>

<script type="text/javascript">
  $(function() {
  $('#user_department_id').change(function() {
    console.log("user_department_id has changed! Id is: " + $(this).val());
    //$('#user_user_id').replaceWith('<input id="user_user_id" name="#user_user_id" readonly="readonly" value="'+ $(this).val()+ '">');
    //$('#user_user_id').val($(this).val());
    $.ajax({
      type:"GET",
      contentType: "application/json; charset=utf-8",
      url:"/departments/retriever",
      data: {department_id: $(this).val()},
      dataType:"json",
      success: function(result){
        console.log("Server responded with " +result);
        $('#user_user_id').replaceWith('<input id="user_user_id" name="#user_user_id" class = "form-control" readonly="readonly" value="'+ result+ '">');
      },
      error: function() {
        console.log("There's something wrong!");
      } 
    });
  });
});
</script>



<div class="row justify-content-center">
  <div class="col-12">
    <%= form_with(model: user, local: true) do |form| %>
      
        <h4 >Add/Edit User</h4>
        <% if user.errors.any? %>
            <% user.errors.full_messages.each do |message| %>
              <p class="card-text"><%= message %><p>
            <% end %>
          </p>
        <% end %>

        <div class="form-group">
          <label for="exampleInputEmail1">Username</label>
          <%= form.text_field :username, :class=>"form-control" %>
        </div>

        <div class="field form-group">
          <label for="exampleInputEmail1">First Name</label>
          <%= form.text_field :fname, :class=>"form-control" %>
        </div>

        <div class="field form-group">
          <label for="exampleInputEmail1">Last Name</label>
          <%= form.text_field :lname, :class=>"form-control" %>
        </div>

        <div class="field form-group">
          <label for="exampleInputEmail1">Email</label>
          <%= form.text_field :email, :class=>"form-control" %>
        </div>

        <div class="field form-group">
          <label for="exampleInputEmail1">Password</label>
          <%= form.password_field :password, :class=>"form-control" %>
        </div>

        <div class="field form-group" style="padding-top: 5px">
          <label for="exampleInputEmail1">Confirm Password</label>
          <%= form.password_field :password_confirmation, :class=>"form-control" %>
        </div>

        <div class="field form-group" style="padding-top: 5px">
          <label for="exampleInputEmail1">Designation</label>
          <%= form.collection_select(:role_id, Role.all, :id, :name, {:prompt => 'Select Role'}, {class: 'form-control' }) %>
        </div>

        <div class="field form-group" style="padding-top: 5px">
          <label for="exampleInputEmail1">Supervisor</label>
          <%= form.collection_select(:user_id, User.all, :id, :fname_with_lname, {:prompt => 'Specify Supervisor'}, {class: 'form-control' }) %>
        </div>

        <div class="field form-group" style="padding-top: 5px">
          <label for="exampleInputEmail1">Department</label>
          <%= form.collection_select(:department_id, Department.all, :id, :name, {:prompt => 'Specify Department'}, {class: 'form-control' }) %>
        </div>

     

      <div class="mt-5 text-right">
      <%= link_to 'Back', users_path, { class: 'btn btn-danger'} %>
        <%= form.submit :submit , class: 'btn btn-primary' %>
      </div>
    <% end %>  
  </div>
</div>

app/views/users/_new.html.erb
	<div class="modal-header">
	  
	  <h4 class="modal-title" id="myModalLabel">ADD USER ACCOUNT</h4>
	  <button type="button" class="close" data-dismiss="modal">x</button>
	</div>
	<div class="modal-body">
		<%= form_with(model: @user, local: true) do |form| %>
		  <% if @user.errors.any? %>
		  	<div id="error_explanation">
		      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

		      <ul>
		      <% user.errors.full_messages.each do |message| %>
		        <li><%= message %></li>
		      <% end %>
		      </ul>
		    </div>
		  <% end %>
		  <div class = "row">
			  <div class="col-md-2">
				  <div class="field form-group ">
				    <%= form.label :username, :class => "control-label" %>
				  </div>  

				  <div class="field form-group mt-4 pt-2">
				    <%= form.label "First_Name" %>
				  </div>		    

				  <div class="field form-group mt-4 pt-2">
				    <%= form.label "Last_Name" %>
				  </div>

				  <div class="field form-group mt-4 pt-2">
				    <%= form.label :email %>
				  </div>
			  </div>
					
			  <div class ="col-md-4">
				  <div class="field form-group">
				    <%= form.text_field :username, :class => "form-control" %>
				  </div>  

				  <div class="field form-group">
				    <%= form.text_field :fname, :class => "form-control" %>
				  </div>		    

				  <div class="field form-group">
				    <%= form.text_field :lname, :class => "form-control" %>
				  </div>

				  <div class="field form-group">
				    <%= form.text_field :email, :class => "form-control" %>
				  </div>
			  </div>
		  
		  
			  <div class="col-md-2">
				  <div class="field form-group">
				    <%= form.label :password %>
				    <p id="prompter"></p>
				    
					</div>  
					
					<div class="field form-group mt-4 pt-2">
					<%= form.label "Re-enter" %>
					</div>

				  <div class="field form-group mt-4 pt-2">
				    <%= form.label "designation" %>
				  </div>		    

				  <div class="field form-group mt-4 pt-2">
				    <%= form.label "Supervisor" %>
				  </div>

				  <div class="field form-group mt-4 pt-2">
				    <%= form.label :department_id %>
				  </div>
			  </div>
					
			  <div class ="col-md-4">
				  <div class="field form-group">
				    <%= form.password_field :password, :id => "pass_id", :class => "form-control" %>
				    <p></p>
				    <%= form.password_field :password_confirmation, :placeholder => "Confirm Password", :id => "conf_pass_id", :class => "form-control" %>
				  </div>  

				  <div class="field form-group">
				    <%= form.collection_select(:role_id, Role.all, :id, :name, {:prompt => 'Select Role'}, {:class => 'form-control'}) %>
				  </div>		    

				  <div class="field form-group">
				    <%= form.collection_select(:user_id, User.all, :id, :fname, {:prompt => 'Specify Supervisor'}, {:class => 'form-control'}) %>
				  </div>

				  <div class="field form-group">
				  	
				    <%= form.collection_select(:department_id, Department.all, :id, :name, {:prompt => 'Specify Department'}, {:class => 'form-control'}) %>
				  </div>
			  </div>
		  </div>

		  <div class="modal-footer">
		    <%= form.submit "Add", :class => "btn btn-secondary", :id => "signup_submit" %>
		  </div>

		<% end %>


	</div>

app/views/users/edit.html.erb
<div class="container py-5">

<%= render 'form', user: @user %>

<% link_to 'Show', @user %>
</div>

app/views/users/index.html.erb
<% if User.where("id = ?", session[:user_id]).pluck(:role_id).first != 1 %>
  <% controller.redirect_to documents_url %>
<% end %>

<div class="container" style="margin-bottom:20px; padding: 3rem 0;">

<!-- deleted checker for user session -->

<p id="notice"><%= notice %></p>
<h1>Users</h1>
<div class="table-responsive">
<table class = "table-hover table-bordered table-condensed table">
  <thead>
    <tr>
      <th>Username</th>
      <th>Fname</th>
      <th>Lname</th>
      <th>Email</th>
      <th>Role</th>
      <th>Supervisor</th>
      <th>Department</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.fname %></td>
        <td><%= user.lname %></td>
        <td><%= user.email %></td>
        
        <td><%= Role.where("id = ?", user.role_id).pluck(:name).first %></td>
        <td><%= User.where("id = ?", user.user_id).pluck(:fname).first.to_s + " " + User.where("id = ?", user.user_id).pluck(:lname).first.to_s %></td>
        <td><%= Department.where("id = ?", user.department_id).pluck(:name).first %></td>
        <% link_to 'Show', user %>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, class: 'text-danger', data: { confirm: 'Are you sure to delete this data?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
</div>

app/views/users/new.html - backup.erb
<h1>New User</h1>



<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/new.html.erb
<%= render 'form', user: @user %>

app/views/users/new.js.erb
$("#modal-window").find(".modal-content").html("<%= j (render 'new') %>");
$("#modal-window").modal();

function checker() {
	console.log("This is being called");
	if ($('#conf_pass_id').val() != $('#pass_id').val()) {
			console.log("Not Match!");
			$('#prompter').html("Password not match!");
			$('#signup_submit').attr('disabled', 'disabled');
	}
	else {
		$('#prompter').html("");
		$('#signup_submit').removeAttr('disabled');	
	}
}

$(function(){
  $('#signup_submit').attr('disabled', 'disabled');
  $("#conf_pass_id").keyup(function() {
		console.log("conf_pass_id is changed!");
		checker();
	});
});

$(function() {
	$('#user_department_id').change(function() {
		console.log("user_department_id has changed! Id is: " + $(this).val());
		//$('#user_user_id').replaceWith('<input id="user_user_id" name="#user_user_id" readonly="readonly" value="'+ $(this).val()+ '">');
		//$('#user_user_id').val($(this).val());
		$.ajax({
		  type:"GET",
		  contentType: "application/json; charset=utf-8",
		  url:"/departments/retriever",
		  data: {department_id: $(this).val()},
		  dataType:"json",
		  success: function(result){
		    console.log("Server responded with " +result);
		    $('#user_user_id').replaceWith('<input id="user_user_id" name="#user_user_id" class = "form-control" readonly="readonly" value="'+ result+ '">');
		  },
		  error: function() {
		  	console.log("There's something wrong!");	
		  } 
		});
	});
});

app/views/users/show.html.erb
<% if User.where("id = ?", session[:user_id]).pluck(:role_id).first != 1 %>
  <% controller.redirect_to 'http://localhost:3000/documents' %>
<% end %>

<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<p>
  <strong>Fname:</strong>
  <%= @user.fname %>
</p>

<p>
  <strong>Lname:</strong>
  <%= @user.lname %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Password digest:</strong>
  <%= @user.password_digest %>
</p>

<p>
  <strong>Role:</strong>
  <%= @user.role_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @user.user_id %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>