config/routes.rb
Rails.application.routes.draw do
  resources :document_histories
  resources :permissions
  resources :documents
  resources :departments do
    collection do
      get 'retriever'
    end
  end
  
  resources :roles
  resources :user_logins
  get 'sessions/new'
  get 'documents/:id/viewer', to: 'documents#viewer', as: 'view_history'
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  #get '*path' => redirect('/login')

  resources :users

  resources :sessions
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/document.rb
class Document < ApplicationRecord

	validates_uniqueness_of :subject
	validates :subject, length: { in: 5..30, too_short: "^Subject name is too short", too_long: "^Subject name is too long" }
	
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_action :set_document, only: [:show, :edit, :update, :destroy]
  before_action :authorize
  # GET /documents
  # GET /documents.json
  def index
    #@documents = Document.all.paginate(:page => params[:page], :per_page => 5)
    dept_id = User.where("id = ?", session[:user_id]).pluck(:department_id).first
    @documents = if params[:subject]
      Document.where('subject LIKE ? AND user_id = ?', "%#{params[:subject]}%", session[:user_id]).or(Document.where('subject LIKE ? AND department_id = ?',"%#{params[:subject]}%", dept_id)).order('id DESC').paginate(:page => params[:page], :per_page => 5)
    else
      Document.where('user_id = ?', session[:user_id]).or(Document.where('department_id = ?', dept_id)).order('id DESC').paginate(:page => params[:page], :per_page => 5)
    end

    if User.where("id = ?", session[:user_id]).pluck(:role_id).first == 1
      @documents = if params[:subject]
        Document.where('subject LIKE ?', "%#{params[:subject]}%").order('id DESC').paginate(:page => params[:page], :per_page => 5)
      else
        Document.all.order('id DESC').paginate(:page => params[:page], :per_page => 5)
      end
    end


    #@document_histories = DocumentHistory.all.paginate(:page => params[:page], :per_page => 5)
    @document_histories = if params[:get_doc_history_subj]
      tmp = DocumentHistory.group("document_id").order('id DESC')
      tmp2 = DocumentHistory.from("(#{tmp.to_sql}) as document_histories").select("document_histories.*").where("document_histories.received_by_office = ? AND document_histories.remarks = ?", dept_id, "Pending").paginate(:page => params[:page], :per_page => 5)
      tmp2.where('subject LIKE ?', "%#{params[:get_doc_history_subj]}%")
    else
      tmp = DocumentHistory.group("document_id").order('id DESC')
      DocumentHistory.from("(#{tmp.to_sql}) as document_histories").select("document_histories.*").where("document_histories.received_by_office = ? AND document_histories.remarks = ?", dept_id, "Pending").paginate(:page => params[:page], :per_page => 5) 
    end
  end

  # GET /documents/1
  # GET /documents/1.json
  def show
  end

  # GET /documents/new
  def new
    @document = Document.new
  end

  # GET /documents/1/edit
  def edit
  end

  def viewer
    @document = DocumentHistory.where("document_id = ?", params[:id])
  end

  # POST /documents
  # POST /documents.json
  def create
    @document = Document.new(document_params)

    respond_to do |format|
      if @document.save
        puts "id is: " + @document.id.to_s
        puts "received_from_name is: " + @document.user_id.to_s
        puts "received_from_office is: " + @document.department_id.to_s
        DocumentHistory.create(:document_id => @document.id, :received_by_name => @document.user_id, :received_by_office => @document.department_id, :received_from_name => @document.user_id, :received_from_office => @document.department_id, :subject => @document.subject, :remarks => @document.status)
        format.html { redirect_to documents_url, notice: 'Document was successfully created.' }
        format.json { render :show, status: :created, location: @document }
      else
        format.html { render :new }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /documents/1
  # PATCH/PUT /documents/1.json
  def update
    respond_to do |format|
      if @document.update(document_params)
        format.html { redirect_to documents_url, notice: 'Document was successfully updated.' }
        format.json { render :show, status: :ok, location: @document }
      else
        format.html { render :edit }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /documents/1
  # DELETE /documents/1.json
  def destroy
    @document.destroy
    respond_to do |format|
      format.html { redirect_to documents_url, notice: 'Document was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_document
      @document = Document.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def document_params
      params.require(:document).permit(:subject, :status, :date_created, :time_created, :user_id, :department_id, :get_doc_history_subj)
    end
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/views/documents/_edit.html.erb
<div class="modal-header">
    
    <h4 class="modal-title" id="myModalLabel">Edit Info</h4>
    <button type="button" class="close" data-dismiss="modal">x</button>
  </div>
  <div class="modal-body">

  <%= form_with(model: @document, local: true) do |form| %>
    <% if @document.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(document.errors.count, "error") %> prohibited this document from being saved:</h2>

        <ul>
        <% document.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= form.label :subject %>
      <%= form.text_field :subject, :readonly => "readonly" %>
    </div>

    <div class="field">
      <%= form.label :status %>
      <%= form.select :status, options_for_select(["Pending","Completed"],"Pending") %>
    </div>

    <div class="field">
      <%= form.label :date_created %>
      <%= form.date_select :date_created %>
    </div>

    <div class="field">
      <%= form.label :time_created %>
      <%= form.time_select :time_created %>
    </div>

      <div class="modal-footer">
        <%= form.submit :class => 'btn btn-primary' %>
      </div>
  <% end %>
</div>

app/views/documents/_form.html.erb
<div class="container py-5">

<%= form_with(model: document, local: true) do |form| %>
  <% if document.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(document.errors.count, "error") %> prohibited this document from being saved:</h2>
      <ul>
      <% document.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="row justify-content-center">
  <div class="col-12">
  <div class="form-group">
    <%= form.label :subject %>
    <%= form.text_field :subject, :readonly => "readonly", :class=>"form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :status %>
    <%= form.text_field :status, :class=>"form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :date_created %>
    <%= form.date_select :date_created, :class=>"form-control col-sm-3" %>
  </div>

  <div class="form-group">
    <%= form.label :time_created %>
    <%= form.time_select :time_created, :class=>"form-control" %>
  </div>

  <div class="actions">
    <%= form.submit class: 'btn btn-primary' %>
  </div>
</div>
</div>
<% end %>
</div>

app/views/documents/_new.html.erb
<div class="modal-header">
    
    <h4 class="modal-title" id="myModalLabel">Add new document</h4>
    <button type="button" class="close" data-dismiss="modal">x</button>
  </div>
  <div class="modal-body">

  <%= form_with(model: @document, local: true) do |form| %>
    <% if @document.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(document.errors.count, "error") %> prohibited this document from being saved:</h2>

        <ul>
        <% document.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group row">
    <label class="col-sm-3 col-form-label">Subject</label>
    <div class="col-sm-9">
    <%= form.text_field :subject, :class => "form-control" %>
    </div>
  </div>

  <div class="form-group row">
    <label class="col-sm-3 col-form-label">Status</label>
    <div class="col-sm-9">
    <%= form.select :status, options_for_select(["Pending","Completed", "Cancelled"],"Pending"), {}, { :class => 'form-control' } %>
    </div>
  </div>

  <div class="form-group row">
    <label class="col-sm-3 col-form-label">Date Created</label>
    <div class="col-sm-9">
    <%= form.date_select :date_created, {}, { :class => ' col-sm-3' } %>
    </div>
  </div>  

  <div class="form-group row">
    <label class="col-sm-3 col-form-label">Time Created</label>
    <div class="col-sm-9">
    <%= form.time_select :time_created, {}, { :class => ' col-sm-3' } %>
    </div>
  </div>        

    <div class="field">
      <% form.label "Creator" %>
      <%= form.hidden_field :user_id, :value => session[:user_id] %>
    </div>

    <div class="field">
      <% form.label "Department" %>
      <% department_id = User.where("id = ?", session[:user_id]).pluck(:department_id).first %>
      <%= form.hidden_field :department_id, :value => department_id %>
    </div>   

    <div class="modal-footer">
      <%= form.submit :class => 'btn btn-secondary' %>
    </div>
  <% end %>

app/views/documents/_show.html.erb
<div class="modal-header">
    
    <h4 class="modal-title" id="myModalLabel">Edit Info</h4>
    <button type="button" class="close" data-dismiss="modal">x</button>
  </div>
  <div class="modal-body">

  <%= form_with(model: @document, local: true) do |form| %>
    <% if @document.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(document.errors.count, "error") %> prohibited this document from being saved:</h2>

        <ul>
        <% document.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group row">
    <label class="col-sm-3 col-form-label">Subject</label>
    <div class="col-sm-9">
    <%= form.text_field :subject, :readonly => "readonly", :class => "form-control" %>
    </div>
  </div>

  <div class="form-group row">
    <label class="col-sm-3 col-form-label">Status</label>
    <div class="col-sm-9">
    <%= form.select :status, options_for_select(["Pending","Completed"],"Pending"), {}, { :class => 'form-control' } %>
    </div>
  </div>

  <div class="form-group row">
    <label class="col-sm-3 col-form-label">Date Created</label>
    <div class="col-sm-9">
    <%= form.date_select :date_created, {}, { :class => ' col-sm-3' } %>
    </div>
  </div>

  <div class="form-group row">
    <label class="col-sm-3 col-form-label">Time Created</label>
    <div class="col-sm-9">
    <%= form.time_select :time_created, {}, { :class => ' col-sm-3' } %>
    </div>
  </div>

  <div class="modal-footer">
        <%= form.submit :class => 'btn btn-secondary' %>
    </div>
  <% end %>
</div>

app/views/documents/edit.html.erb
<h1>Editing Document</h1>

<%= render 'form', document: @document %>

<%= link_to 'Show', @document %> |
<%= link_to 'Back', documents_path %>

app/views/documents/index.html.erb
<div class="container py-5" style="margin-bottom:20px; padding: 3rem 0;">
<p id="notice"><%= notice %></p>
<h3>Documents</h3>
  <div style="float: right;">
  <%= form_tag(documents_path, method: :get) do %>
    <div class="input-group mb-3">
    <%= text_field_tag :subject, params[:subject], :placeholder => "Search for a document", :class => "form-control" %>
      <div class="input-group-append">
        <%= submit_tag 'Search', name: nil, class:"btn btn-primary" %>
      </div>
    </div>
  <% end %>
  </div>
<div class="table-responsive">
<table class = "table-hover table-bordered table-condensed table">
  <thead>
    <tr>
      <th>Subject</th>
      <th>Status</th>
      <th>Date created</th>
      <th>Time created</th>
      <th>Requested by</th>
      <th>Current Location</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <% department_id = User.where("id = ?", session[:user_id]).pluck(:department_id).first %>
  <tbody>
    <% @documents.each do |document| %>
      <tr>
        <td><%= document.subject %></td>
        <td><%= document.status %></td>
        <td><%= document.date_created %></td>
        <td><%= document.time_created.strftime("%I:%M %p") %></td>
        <td><%= User.where("id = ?", document.user_id).pluck(:fname).first.to_s + " " + User.where("id = ?", document.user_id).pluck(:lname).first.to_s %></td>
        <td><% dh = DocumentHistory.where("document_id = ?", document.id).order('id DESC').pluck(:received_by_office).first %>
          <%= Department.where("id = ?", dh).pluck(:name).first %>
        </td>
        <td>
          <%= link_to 'Edit', document,  {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#modal-window-show-docs'}  %>
        </td>
        <td><%= link_to 'View History', view_history_path(document) %></td>
        <td><%= link_to 'Destroy', document, method: :delete, data: { confirm: 'Are you sure?' }, class: 'text-danger' %></td>
      </tr>
    <% end %>

  </tbody>
  
  <div class="digg_pagination">
    <div class="page_info">
    <%= page_entries_info @documents %>
    </div>
    <div class="flickr_pagination">
        <%= will_paginate @documents, :container => false %>
    </div>
  </div>
</table>
</div>


<% if User.where("id = ?", session[:user_id]).pluck(:role_id).first != 1 %>
<br />
	<%= link_to 'New Document', new_document_path, {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#modal-window-new-docs', class: 'btn btn-secondary'} %>
	<% link_to 'Forward Document', new_document_history_path, {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#modal-window-new-history', class: 'btn btn-secondary'} %>
	<h3 class="mt-5">Documents On-Hand</h3>
	<div style="float: right;">
	  <%= form_tag(documents_path, method: :get) do %>
	    <div class="input-group mb-3">
	      <%= text_field_tag :get_doc_history_subj, params[:get_doc_history_subj], :placeholder => "Find documents on-hand", :class =>"form-control" %>
	      <div class="input-group-append">
	        <%= submit_tag 'Search', name: nil, class:"btn btn-primary" %>
	      </div>
	    </div>
	  <% end %>
	</div>

	<div class="table-responsive">
	<table class = "table-hover table-bordered table-condensed table">
	  <thead>
	    <tr>
	      <th>Subject</th>
	      <th>Status</th>
	      <th>Requesting Office</th>
	      <th>Date & Time Received</th>
	      <th>Received by</th>
	      <th>Forwarding Office</th>
	      <th>Forwarded by</th>
	      <% if User.where("id = ?", session[:user_id]).pluck(:role_id).first == 1 %>
	      	<th colspan="2"></th>
	      <% end %>
	    </tr>
	  </thead>

	  <% department_id = User.where("id = ?", session[:user_id]).pluck(:department_id).first %>
	  <tbody>
	    <% @document_histories.each do |document| %>
	      <tr>
	        <td><%= document.subject %></td>
	        <td><%= document.remarks %></td>
	        <td>
	        	<% u_id = Document.where("id = ?", document.document_id).pluck(:user_id).first %>
	        	<% d_id = User.where("id = ?", u_id).pluck(:department_id).first %>
	        	<%= Department.where("id = ?", d_id).pluck(:name).first %>
	        </td>
	        <td><%= document.created_at.strftime("%Y/%m/%d %I:%M %p") %></td>
	        <% if document.received_by_name != document.received_from_name %>
		      <td><%= User.where("id = ?", document.received_by_name).pluck(:fname).first.to_s + " " + User.where("id = ?", document.received_by_name).pluck(:lname).first.to_s %></td>
		      <td><%= Department.where("id = ?", document.received_from_office).pluck(:name).first %></td>
		      <td><%= User.where("id = ?", document.received_from_name).pluck(:fname).first.to_s + " " + User.where("id = ?", document.received_from_name).pluck(:lname).first.to_s %></td>
	        <% else %>
	          <td>N/A</td>
	          <td>N/A</td>
	          <td>N/A</td>
	        <% end %>
	        <% if User.where("id = ?", session[:user_id]).pluck(:role_id).first == 1 %>
	          <td>
		          <%= link_to 'Edit', document,  {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#modal-window-show-docs'}  %>
	          </td>
	          <td><%= link_to 'Destroy', document, method: :delete, data: { confirm: 'Are you sure?' }, class: 'text-danger' %></td>
		    <% end %>
	      </tr>
	    <% end %>
	    <div>
	    <div class="digg_pagination">
	    <div class="page_info">
	      <%= page_entries_info @document_histories %>
	    </div>
	  </div>
	    <div class="flickr_pagination">
	        <%= will_paginate @document_histories, :container => false %>
	    </div>
	  </div>

	  </tbody>
	</table>
	</div>
	<% link_to 'New Document', new_document_path, {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#modal-window-new-docs', class: 'btn btn-secondary'} %>
	<%= link_to 'Forward Document', new_document_history_path, {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#modal-window-new-history', class: 'btn btn-secondary'} %>
	</div>
<% end %>

app/views/documents/new.html.erb
<h1>New Document</h1>

<%= render 'form', document: @document %>

<%= link_to 'Back', documents_path, class: 'btn btn-info' %>

app/views/documents/new.js.erb
$("#modal-window-new-docs").find(".modal-content").html("<%= j (render 'new') %>");
$("#modal-window-new-docs").modal();

app/views/documents/show.html.erb
<% if User.where("id = ?", session[:user_id]).pluck(:role_id).first != 1 %>
  <% controller.redirect_to 'http://localhost:3000/documents' %>
<% end %>

<p id="notice"><%= notice %></p>

<p>
  <strong>Subject:</strong>
  <%= @document.subject %>
</p>

<p>
  <strong>Status:</strong>
  <%= @document.status %>
</p>

<p>
  <strong>Date created:</strong>
  <%= @document.date_created %>
</p>

<p>
  <strong>Time created:</strong>
  <%= @document.time_created %>
</p>

<%= link_to 'Edit', edit_document_path(@document) %> |
<%= link_to 'Back', documents_path %>

app/views/documents/show.js.erb
$("#modal-window-show-docs").find(".modal-content").html("<%= j (render 'show') %>");
$("#modal-window-show-docs").modal();

app/views/documents/viewer.html.erb
<p id="notice"><%= notice %></p>

<h1>Document Histories</h1>

<center>
<div class="table-responsive">
<table class = "table-hover table-bordered table-condensed table" style="width: 85%">
  <thead>
    <tr>
      <th>Document ID</th>
      <th>Subject</th>
      <th>Received by</th>
      <th>Receiving Office</th>
      <th>Received from</th>
      <th>Forwarding Office</th>
      <th>Date received</th>
      <!-- <th>Length of stay</th> -->
      <th>Remarks</th>
      <!-- <th>Max stay</th> -->
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @document.each do |document_history| %>
      <tr>
        <td><%= document_history.document_id %></td>
        <td><%= document_history.subject %></td>
        <td><%= User.where("id = ?", document_history.received_by_name).pluck(:fname).first.to_s + " " + User.where("id = ?", document_history.received_by_name).pluck(:lname).first.to_s %></td>
        <td>
          <%= Department.where("id = ?", document_history.received_by_office).pluck(:name).first %></td>
        <td><%= User.where("id = ?", document_history.received_from_name).pluck(:fname).first.to_s + " " + User.where("id = ?", document_history.received_from_name).pluck(:lname).first.to_s %></td>
        <td><%= Department.where("id = ?", document_history.received_from_office).pluck(:name).first %></td>
        <td><%= document_history.created_at.strftime("%Y/%m/%d %I:%M %p") %></td>
        <!-- <td><%= document_history.length_of_stay %></td> -->
        <td><%= document_history.remarks %></td>
        <!-- <td><%= document_history.max_stay %></td> -->
        <% link_to 'Show', document_history %>
        <td><%= link_to 'Edit', edit_document_history_path(document_history) %></td>
        <td><%= link_to 'Destroy', document_history, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
</center>

<%= link_to 'Back', documents_path, :class => 'btn btn-primary' %>