config/routes.rb
Rails.application.routes.draw do
  resources :document_histories
  resources :permissions
  resources :documents
  resources :departments do
    collection do
      get 'retriever'
    end
  end
  
  resources :roles
  resources :user_logins
  get 'sessions/new'
  get 'documents/:id/viewer', to: 'documents#viewer', as: 'view_history'
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  #get '*path' => redirect('/login')

  resources :users

  resources :sessions
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/role.rb
class Role < ApplicationRecord
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  before_action :set_role, only: [:show, :edit, :update, :destroy]
  before_action :authorize
  # GET /roles
  # GET /roles.json
  def index
    @roles = Role.all
  end

  # GET /roles/1
  # GET /roles/1.json
  def show
  end

  # GET /roles/new
  def new
    @role = Role.new
  end

  # GET /roles/1/edit
  def edit
  end

  # POST /roles
  # POST /roles.json
  def create
    @role = Role.new(role_params)

    respond_to do |format|
      if @role.save
        format.html { redirect_to @role, notice: 'Role was successfully created.' }
        format.json { render :show, status: :created, location: @role }
      else
        format.html { render :new }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /roles/1
  # PATCH/PUT /roles/1.json
  def update
    respond_to do |format|
      if @role.update(role_params)
        format.html { redirect_to @role, notice: 'Role was successfully updated.' }
        format.json { render :show, status: :ok, location: @role }
      else
        format.html { render :edit }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /roles/1
  # DELETE /roles/1.json
  def destroy
    @role.destroy
    respond_to do |format|
      format.html { redirect_to roles_url, notice: 'Role was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_role
      @role = Role.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def role_params
      params.require(:role).permit(:name, :description)
    end
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/views/roles/_form.html.erb
<% if User.where("id = ?", session[:user_id]).pluck(:role_id).first != 1 %>
  <% controller.redirect_to 'http://localhost:3000/documents' %>
<% end %>

<%= form_with(model: role, local: true) do |form| %>
  <% if role.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(role.errors.count, "error") %> prohibited this role from being saved:</h2>

      <ul>
      <% role.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group row">
    <label class="col-sm-2 col-form-label"><%= form.label :name %></label>
    <div class="col-sm-10">
    <%= form.text_field :name, :class => "form-control" %>
  </div>
  </div>

  <div class="form-group row">
    <label class="col-sm-2 col-form-label"><%= form.label :description %></label>
    <div class="col-sm-10">
    <%= form.text_area :description, :class => "form-control" %>
  </div>
  </div>

  <div class="mt-5 text-right">
  <%= link_to 'Back', roles_path, class: 'btn btn-danger' %>
    <%= form.submit :class => 'btn btn-primary' %>
   
  </div>

<% end %>

app/views/roles/edit.html.erb
<div class="container" style="margin-bottom:20px; padding: 3rem 0;">
<h4>Editing Role</h4>
<%= render 'form', role: @role %>
</div>

app/views/roles/index.html.erb
<% if User.where("id = ?", session[:user_id]).pluck(:role_id).first != 1 %>
  <% controller.redirect_to 'http://localhost:3000/documents' %>
<% end %>

<div class="container" style="margin-bottom:20px; padding: 3rem 0;">
<p id="notice"><%= notice %></p>
<h1>Roles</h1>
<div class="table-responsive">
<table class = "table-hover table-bordered table-condensed table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @roles.each do |role| %>
      <tr>
        <td><%= role.name %></td>
        <td><%= role.description %></td>
        
        <td><%= link_to 'Edit', edit_role_path(role), { class: ''} %></td>
        <td><%= link_to 'Destroy', role,  class: 'text-danger', method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<%= link_to 'New Role', new_role_path, class: 'btn btn-secondary' %>
</div>

app/views/roles/new.html.erb
<div class="container" style="margin-bottom:20px; padding: 3rem 0;"><p id="notice"><%= notice %></p>
<h4>New Role</h4>
<%= render 'form', role: @role %>
</div>

app/views/roles/show.html.erb
<% if User.where("id = ?", session[:user_id]).pluck(:role_id).first != 1 %>
  <% controller.redirect_to 'http://localhost:3000/documents' %>
<% end %>

<div class="container" style="margin-bottom:20px; padding: 3rem 0;"><p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @role.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @role.description %>
</p>

<%= link_to 'Edit', edit_role_path(@role) %> |
<%= link_to 'Back', roles_path %>

</div>