config/routes.rb
Rails.application.routes.draw do
  resources :document_histories
  resources :permissions
  resources :documents
  resources :departments do
    collection do
      get 'retriever'
    end
  end
  
  resources :roles
  resources :user_logins
  get 'sessions/new'
  get 'documents/:id/viewer', to: 'documents#viewer', as: 'view_history'
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  #get '*path' => redirect('/login')

  resources :users

  resources :sessions
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DocumentTrackingSystemDeped</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag "pagination" %>
  </head>

  <body>
    <% role_id = User.where("id = ?", session[:user_id]).pluck(:role_id).first %>

    <div id="modal-window" class="modal hide fade form-horizontal" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-dialog modal-lg modal-dialog-centered" role="document">
        <div class="modal-content" style="width:700px;" ></div>
      </div>
    </div>

    <div id="modal-window-show-dept" class="modal hide fade form-horizontal" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content" style="width:500px;" ></div>
      </div>
    </div>

    <div id="modal-window-show-docs" class="modal hide fade form-horizontal" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content" style="width:600px;" ></div>
      </div>
    </div>

    <div id="modal-window-new-docs" class="modal hide fade form-horizontal" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content" style="width:600px;" ></div>
      </div>
    </div>

    <div id="modal-window-new-history" class="modal hide fade form-horizontal" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content" style="width:600px;" ></div>
      </div>
    </div>

    <nav class="navbar navbar-dark bg-dark">
        <div class="navbar-header">
          <%= image_tag "deped-logo.png", :style => "height:50px; width:50px" %>
          <a class="navbar-brand" href="/documents">Document Tracking System</a>
          <% if session[:user_id] != nil && role_id == 1 %>
            <a class="navbar-brand" href="/users">Users</a>
            <a class="navbar-brand" href="/departments">Departments</a>
            <a class="navbar-brand" href="/roles">Roles</a>
          <% end %>
        </div>
      <div style="float: right;" class ="page-header">
      <% if role_id == 1 %>
        <%= link_to 'Add user', new_user_path,  {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#modal-window', class: 'btn btn-outline-primary'}  %>
      <% end %>
      <% link_to 'Add user', new_user_path,  {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#modal-window', class: 'btn btn-outline-primary'}  %>
      <% if current_user %>
        <label style="color:white">Logged in as <%= current_user.username %>.  </label>
        <%= link_to "Log Out", logout_path, { class: 'btn btn-outline-primary'} %>
      <% else %>
        <% link_to "Sign Up", signup_path %>
        <%= link_to "Log In", login_path, { class: 'btn btn-outline-primary'} %>
      <% end %>
    </div>
    </nav>
    <%= yield %>
  </body>
</html>